FROM ocaml/opam:alpine-ocaml-4.14

COPY --chown=opam *.opam ocaml-platform/

WORKDIR ocaml-platform/

RUN opam install -y --deps-only --with-test --with-doc .

COPY --chown=opam dune* .
COPY --chown=opam src src

COPY test/tests/build.sh .

ARG TARGETOS
ENV TARGETOS=$TARGETOS
ARG TARGETARCH
ENV TARGETARCH=$TARGETARCH

RUN bash build.sh
