ARG TARGETPLATFORM=$TARGETPLATFORM

FROM ocaml-platform-build-$TARGETPLATFORM:latest as base

FROM ocaml/opam:ubuntu-ocaml-4.13

COPY test/tests/small-project.sh .

RUN bash small-project.sh

COPY --from=base /home/opam/ocaml-platform/_build/default/src/bin/main.exe /usr/local/bin/ocaml-platform
