ARG TARGETPLATFORM=$TARGETPLATFORM

FROM ocaml-platform-build-$TARGETPLATFORM:latest as base

FROM ubuntu:20.04

RUN apt update && apt install -y \
    gcc make patch unzip bubblewrap curl rsync opam libgmp-dev libssl-dev pkg-config

RUN useradd -ms /bin/bash user
WORKDIR /home/user
USER user

RUN opam init --disable-sandboxing --yes

COPY test/tests/install.sh .
COPY --from=base /usr/local/bin/ocaml-platform /usr/local/bin/ocaml-platform

RUN bash install.sh
