ARG TARGETPLATFORM=$TARGETPLATFORM

FROM ocaml-platform-build-$TARGETPLATFORM:latest as base

FROM ocaml-platform-install-in-small-project-$TARGETPLATFORM:latest

COPY --from=base /usr/local/bin/ocaml-platform /usr/local/bin/ocaml-platform

RUN true
    # https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer

COPY test/tests/re-install-in-small-project.sh .

RUN bash re-install-in-small-project.sh
