ARG TARGETPLATFORM=$TARGETPLATFORM
FROM ocaml-platform-build-$TARGETPLATFORM:latest as base
FROM ocaml/opam:ubuntu-ocaml-4.13

COPY test/tests/small-project.sh .
RUN bash small-project.sh
WORKDIR helloworld

RUN opam switch create . 4.13.1

COPY --from=base /usr/local/bin/ocaml-platform /usr/local/bin/ocaml-platform

RUN true
    # https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer

COPY test/tests/install-in-small-project.sh .

RUN bash install-in-small-project.sh
