ARG TARGETPLATFORM=$TARGETPLATFORM

FROM ocaml-platform-build-$TARGETPLATFORM:latest as base

FROM ocaml-platform-install-$TARGETPLATFORM:latest

COPY --from=base /usr/local/bin/ocaml-platform /usr/local/bin/ocaml-platform

RUN true
    # https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer

COPY test/tests/switch-5.0.sh .

RUN bash switch-5.0.sh

COPY test/tests/ocaml5.sh .

RUN bash ocaml5.sh

