ARG TARGETPLATFORM=$TARGETPLATFORM

FROM ocaml-platform-build-$TARGETPLATFORM:latest as base

FROM panglesd/ocaml-platform-installer:ocaml-platform-install-linux_amd64-v0.7.0

COPY --from=base /usr/local/bin/ocaml-platform /usr/local/bin/ocaml-platform

# Too complex to make a good test. Migration should be hand-tested.
