ARG TARGETPLATFORM=$TARGETPLATFORM
FROM ocaml-platform-build-$TARGETPLATFORM:latest as base
# Avoid rebuilding all the tools
FROM ocaml-platform-install-in-small-project-$TARGETPLATFORM:latest

# Install a different version than specified in the script
RUN opam install -y ocamlformat.0.23.0

COPY --from=base /usr/local/bin/ocaml-platform /usr/local/bin/ocaml-platform

RUN true
    # https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer

COPY test/tests/ocamlformat_user_installed.sh .

RUN bash ocamlformat_user_installed.sh
