ARG TARGETPLATFORM=$TARGETPLATFORM

FROM ocaml-platform-build-$TARGETPLATFORM:latest as base

FROM ocaml-platform-install-$TARGETPLATFORM:latest

COPY --from=base /home/opam/ocaml-platform/_build/default/src/bin/main.exe /usr/local/bin/ocaml-platform

RUN true

COPY test/tests/reinstall_cached.sh .

RUN bash reinstall_cached.sh
